# Generated by Django 4.2.7 on 2025-07-29 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_ves', models.DecimalField(decimal_places=4, help_text='Exchange rate at the time of order/payment', max_digits=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, help_text='Amount in USD', max_digits=10)),
                ('amount_ves', models.DecimalField(decimal_places=2, help_text='Equivalent amount in VES', max_digits=15)),
                ('snapshot_timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rate_snapshot', to='orders.order')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rate_snapshot', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Exchange Rate Snapshot',
                'verbose_name_plural': 'Exchange Rate Snapshots',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_ves', models.DecimalField(decimal_places=4, help_text='Exchange rate from USD to VES (Bolívares)', max_digits=10)),
                ('source', models.CharField(choices=[('google_finance', 'Google Finance'), ('exchangerate_host', 'Exchangerate.host'), ('open_exchange_rates', 'Open Exchange Rates'), ('manual', 'Manual Override'), ('fallback', 'Fallback Source')], default='google_finance', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this is the current active rate')),
                ('fetch_success', models.BooleanField(default=True, help_text='Whether the rate was successfully fetched')),
                ('error_message', models.TextField(blank=True, help_text='Error message if fetch failed')),
                ('change_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage change from previous rate', max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate Log',
                'verbose_name_plural': 'Exchange Rate Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'is_active'], name='payments_ex_timesta_1d7317_idx'), models.Index(fields=['source', 'timestamp'], name='payments_ex_source_c0acfe_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('high_change', 'High Percentage Change'), ('fetch_error', 'Fetch Error'), ('manual_override', 'Manual Override'), ('source_fallback', 'Source Fallback')], max_length=20)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, help_text='Threshold value that triggered the alert', max_digits=5, null=True)),
                ('message', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exchange_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='payments.exchangeratelog')),
            ],
            options={
                'verbose_name': 'Exchange Rate Alert',
                'verbose_name_plural': 'Exchange Rate Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
