# Generated by Django 4.2.7 on 2025-07-29 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_exchangeratesnapshot_exchangeratelog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoMovilBankCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(max_length=10, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pago Móvil Bank Code',
                'verbose_name_plural': 'Pago Móvil Bank Codes',
                'ordering': ['bank_name'],
            },
        ),
        migrations.CreateModel(
            name='PagoMovilRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.CharField(help_text='Recipient ID (starts with V or J)', max_length=20)),
                ('recipient_phone', models.CharField(help_text='Registered phone number for Pago Móvil', max_length=20)),
                ('recipient_name', models.CharField(help_text='Recipient name', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='payments.pagomovilbankcode')),
            ],
            options={
                'verbose_name': 'Pago Móvil Recipient',
                'verbose_name_plural': 'Pago Móvil Recipients',
                'unique_together': {('bank_code', 'recipient_id', 'recipient_phone')},
            },
        ),
        migrations.CreateModel(
            name='PagoMovilVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(help_text='Sender ID (e.g., V-12345678 or J-12345678-0)', max_length=20)),
                ('sender_phone', models.CharField(help_text='Sender phone number', max_length=20)),
                ('amount_ves', models.DecimalField(decimal_places=2, help_text='Amount in VES', max_digits=15)),
                ('exchange_rate_used', models.DecimalField(decimal_places=4, help_text='Exchange rate at submission time', max_digits=10)),
                ('usd_equivalent', models.DecimalField(decimal_places=2, help_text='USD equivalent amount', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pagomovil_requests', to=settings.AUTH_USER_MODEL)),
                ('bank_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='payments.pagomovilbankcode')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagomovil_requests', to='orders.order')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='payments.pagomovilrecipient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagomovil_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago Móvil Verification Request',
                'verbose_name_plural': 'Pago Móvil Verification Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payments_pa_user_id_35e4a3_idx'), models.Index(fields=['created_at', 'status'], name='payments_pa_created_0e528f_idx')],
            },
        ),
    ]
